### ISSUE TITLE
Remove radio buttons and replace

### ISSUE THREAD

**Issue by itsaljones** [jameshd/playfooty#22]
Instead of 'I can play' 'I cant play' and a submit button. Let's just have two buttons. One for yes and one for no.

**Comment by jameshd** [comment]
I can I can't??? Sounds like a good shout mate.

**Comment by itsaljones** [comment]
Haha yeh, probably go for 'I can play' & 'Not this time'

**Comment by itsaljones** [comment]
Also @jameshd this change needs to occur when you press 'edit' in the team sheet.
