### ISSUE TITLE
Match info on managers link could be presented a little clearer

### ISSUE THREAD

**Issue by adamland** [jameshd/playfooty#28]
For example it would be a little quicker to scan if separated in my opinion e.g.

 23rd December, 2015 7:00 pm
 1 players can attend 
 Match created by ABC - about 1 hour ago 
 Salford Sports Village, Salford, United Kingdom 
 Date picker is broke. American format on .co.uk

Make it the same as the styling on the players link.

**Comment by jameshd** [comment]
this is sorted.
